[2024-12-05 03:12:39,686] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: crypto_data_pipeline.check_api_connection manual__2024-12-05T03:12:38.387350+00:00 [queued]>
[2024-12-05 03:12:39,690] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: crypto_data_pipeline.check_api_connection manual__2024-12-05T03:12:38.387350+00:00 [queued]>
[2024-12-05 03:12:39,690] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-05 03:12:39,690] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2024-12-05 03:12:39,691] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-05 03:12:39,699] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): check_api_connection> on 2024-12-05 03:12:38.387350+00:00
[2024-12-05 03:12:39,701] {standard_task_runner.py:52} INFO - Started process 57 to run task
[2024-12-05 03:12:39,703] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_data_pipeline', 'check_api_connection', 'manual__2024-12-05T03:12:38.387350+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/crypto_data_pipeline.py', '--cfg-path', '/tmp/tmpkrtini6_', '--error-file', '/tmp/tmpsf35tm5w']
[2024-12-05 03:12:39,704] {standard_task_runner.py:80} INFO - Job 3: Subtask check_api_connection
[2024-12-05 03:12:39,744] {task_command.py:369} INFO - Running <TaskInstance: crypto_data_pipeline.check_api_connection manual__2024-12-05T03:12:38.387350+00:00 [running]> on host 85834e6b4d18
[2024-12-05 03:12:39,800] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=crypto_data_pipeline
AIRFLOW_CTX_TASK_ID=check_api_connection
AIRFLOW_CTX_EXECUTION_DATE=2024-12-05T03:12:38.387350+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-05T03:12:38.387350+00:00
[2024-12-05 03:12:39,800] {http.py:97} INFO - Poking: api/v3/coins/markets
[2024-12-05 03:12:39,818] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 112, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 103, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 114, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `coin_gecko_api` isn't defined
[2024-12-05 03:12:39,821] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_pipeline, task_id=check_api_connection, execution_date=20241205T031238, start_date=20241205T031239, end_date=20241205T031239
[2024-12-05 03:12:39,826] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task check_api_connection (The conn_id `coin_gecko_api` isn't defined; 57)
[2024-12-05 03:12:39,835] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-05 03:12:39,864] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
