[2024-12-05 03:17:37,694] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: crypto_data_pipeline.save_to_postgres scheduled__2024-12-05T02:00:00+00:00 [queued]>
[2024-12-05 03:17:37,707] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: crypto_data_pipeline.save_to_postgres scheduled__2024-12-05T02:00:00+00:00 [queued]>
[2024-12-05 03:17:37,707] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-05 03:17:37,707] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2024-12-05 03:17:37,707] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-05 03:17:37,725] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-12-05 02:00:00+00:00
[2024-12-05 03:17:37,729] {standard_task_runner.py:52} INFO - Started process 91 to run task
[2024-12-05 03:17:37,733] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_data_pipeline', 'save_to_***', 'scheduled__2024-12-05T02:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/crypto_data_pipeline.py', '--cfg-path', '/tmp/tmp1my9wllg', '--error-file', '/tmp/tmp7um_lr5y']
[2024-12-05 03:17:37,733] {standard_task_runner.py:80} INFO - Job 9: Subtask save_to_***
[2024-12-05 03:17:37,754] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-05 03:17:37,806] {task_command.py:369} INFO - Running <TaskInstance: crypto_data_pipeline.save_to_postgres scheduled__2024-12-05T02:00:00+00:00 [running]> on host 85834e6b4d18
[2024-12-05 03:17:37,870] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=crypto_data_pipeline
AIRFLOW_CTX_TASK_ID=save_to_***
AIRFLOW_CTX_EXECUTION_DATE=2024-12-05T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-05T02:00:00+00:00
[2024-12-05 03:17:37,871] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_data_pipeline.py", line 55, in save_to_postgres
    dbname="crypto_db", user="postgres", password="postgres", host="localhost"
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-12-05 03:17:37,880] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_pipeline, task_id=save_to_***, execution_date=20241205T020000, start_date=20241205T031737, end_date=20241205T031737
[2024-12-05 03:17:37,886] {standard_task_runner.py:97} ERROR - Failed to execute job 9 for task save_to_*** (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 91)
[2024-12-05 03:17:37,904] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-05 03:17:37,934] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05 03:41:07,165] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: crypto_data_pipeline.save_to_postgres scheduled__2024-12-05T02:00:00+00:00 [queued]>
[2024-12-05 03:41:07,172] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: crypto_data_pipeline.save_to_postgres scheduled__2024-12-05T02:00:00+00:00 [queued]>
[2024-12-05 03:41:07,173] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-05 03:41:07,173] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2024-12-05 03:41:07,173] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-05 03:41:07,183] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): save_to_postgres> on 2024-12-05 02:00:00+00:00
[2024-12-05 03:41:07,185] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2024-12-05 03:41:07,188] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_data_pipeline', 'save_to_***', 'scheduled__2024-12-05T02:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/crypto_data_pipeline.py', '--cfg-path', '/tmp/tmpz6iccqzh', '--error-file', '/tmp/tmppv7vhiia']
[2024-12-05 03:41:07,188] {standard_task_runner.py:80} INFO - Job 10: Subtask save_to_***
[2024-12-05 03:41:07,202] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-05 03:41:07,236] {task_command.py:369} INFO - Running <TaskInstance: crypto_data_pipeline.save_to_postgres scheduled__2024-12-05T02:00:00+00:00 [running]> on host 086bf0bb532a
[2024-12-05 03:41:07,303] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=crypto_data_pipeline
AIRFLOW_CTX_TASK_ID=save_to_***
AIRFLOW_CTX_EXECUTION_DATE=2024-12-05T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-05T02:00:00+00:00
[2024-12-05 03:41:07,310] {python.py:173} INFO - Done. Returned value was: None
[2024-12-05 03:41:07,322] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=crypto_data_pipeline, task_id=save_to_***, execution_date=20241205T020000, start_date=20241205T034107, end_date=20241205T034107
[2024-12-05 03:41:07,359] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-12-05 03:41:07,385] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
